# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Playback.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Playback.proto',
  package='Playback',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ePlayback.proto\x12\x08Playback\"\xaa\x01\n\x08Playback\x12\x11\n\tSessionId\x18\x01 \x02(\x05\x12\x11\n\tChannelId\x18\x02 \x02(\x05\x12\x16\n\x0eTimestampDelta\x18\x03 \x01(\x03\x12\x0f\n\x07Payload\x18\x04 \x03(\x0c\x12\x1a\n\x12LatencyRtpSequence\x18\x05 \x01(\x05\x12\x16\n\x0eLatencyRtpSsrc\x18\x06 \x01(\x05\x12\x1b\n\x13\x44irectorsCutRegions\x18\x07 \x03(\x05'
)




_PLAYBACK = _descriptor.Descriptor(
  name='Playback',
  full_name='Playback.Playback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='SessionId', full_name='Playback.Playback.SessionId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ChannelId', full_name='Playback.Playback.ChannelId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TimestampDelta', full_name='Playback.Playback.TimestampDelta', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Payload', full_name='Playback.Playback.Payload', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LatencyRtpSequence', full_name='Playback.Playback.LatencyRtpSequence', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LatencyRtpSsrc', full_name='Playback.Playback.LatencyRtpSsrc', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DirectorsCutRegions', full_name='Playback.Playback.DirectorsCutRegions', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=199,
)

DESCRIPTOR.message_types_by_name['Playback'] = _PLAYBACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Playback = _reflection.GeneratedProtocolMessageType('Playback', (_message.Message,), {
  'DESCRIPTOR' : _PLAYBACK,
  '__module__' : 'Playback_pb2'
  # @@protoc_insertion_point(class_scope:Playback.Playback)
  })
_sym_db.RegisterMessage(Playback)


# @@protoc_insertion_point(module_scope)
