# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlaybackBegin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PlaybackBegin.proto',
  package='PlaybackBegin',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13PlaybackBegin.proto\x12\rPlaybackBegin\"\xcf\x02\n\rPlaybackBegin\x12\x11\n\tSessionId\x18\x01 \x02(\x05\x12\x35\n\x08\x43hannels\x18\x02 \x03(\x0b\x32#.PlaybackBegin.PlaybackBegin.Stream\x12\x15\n\rSrtpMasterKey\x18\x03 \x03(\x0c\x12\x16\n\x0eSrtpMasterSalt\x18\x04 \x03(\x0c\x12\x0f\n\x07\x46\x61\x63KVal\x18\x05 \x01(\x05\x12\x0f\n\x07\x46\x61\x63NVal\x18\x06 \x01(\x05\x1a\xa2\x01\n\x06Stream\x12\x11\n\tChannelId\x18\x01 \x01(\x05\x12\x11\n\tCodecType\x18\x02 \x01(\x05\x12\x12\n\nSampleRate\x18\x03 \x01(\x05\x12\x13\n\x0bPrivateData\x18\x04 \x03(\x0c\x12\x11\n\tStartTime\x18\x05 \x01(\x01\x12\x0f\n\x07UdpSsrc\x18\x06 \x01(\x05\x12\x14\n\x0cRtpStartTime\x18\x07 \x01(\x05\x12\x0f\n\x07Profile\x18\x08 \x01(\x05'
)




_PLAYBACKBEGIN_STREAM = _descriptor.Descriptor(
  name='Stream',
  full_name='PlaybackBegin.PlaybackBegin.Stream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ChannelId', full_name='PlaybackBegin.PlaybackBegin.Stream.ChannelId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CodecType', full_name='PlaybackBegin.PlaybackBegin.Stream.CodecType', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SampleRate', full_name='PlaybackBegin.PlaybackBegin.Stream.SampleRate', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PrivateData', full_name='PlaybackBegin.PlaybackBegin.Stream.PrivateData', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='StartTime', full_name='PlaybackBegin.PlaybackBegin.Stream.StartTime', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='UdpSsrc', full_name='PlaybackBegin.PlaybackBegin.Stream.UdpSsrc', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RtpStartTime', full_name='PlaybackBegin.PlaybackBegin.Stream.RtpStartTime', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Profile', full_name='PlaybackBegin.PlaybackBegin.Stream.Profile', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=374,
)

_PLAYBACKBEGIN = _descriptor.Descriptor(
  name='PlaybackBegin',
  full_name='PlaybackBegin.PlaybackBegin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='SessionId', full_name='PlaybackBegin.PlaybackBegin.SessionId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Channels', full_name='PlaybackBegin.PlaybackBegin.Channels', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SrtpMasterKey', full_name='PlaybackBegin.PlaybackBegin.SrtpMasterKey', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SrtpMasterSalt', full_name='PlaybackBegin.PlaybackBegin.SrtpMasterSalt', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FacKVal', full_name='PlaybackBegin.PlaybackBegin.FacKVal', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FacNVal', full_name='PlaybackBegin.PlaybackBegin.FacNVal', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PLAYBACKBEGIN_STREAM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=374,
)

_PLAYBACKBEGIN_STREAM.containing_type = _PLAYBACKBEGIN
_PLAYBACKBEGIN.fields_by_name['Channels'].message_type = _PLAYBACKBEGIN_STREAM
DESCRIPTOR.message_types_by_name['PlaybackBegin'] = _PLAYBACKBEGIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlaybackBegin = _reflection.GeneratedProtocolMessageType('PlaybackBegin', (_message.Message,), {

  'Stream' : _reflection.GeneratedProtocolMessageType('Stream', (_message.Message,), {
    'DESCRIPTOR' : _PLAYBACKBEGIN_STREAM,
    '__module__' : 'PlaybackBegin_pb2'
    # @@protoc_insertion_point(class_scope:PlaybackBegin.PlaybackBegin.Stream)
    })
  ,
  'DESCRIPTOR' : _PLAYBACKBEGIN,
  '__module__' : 'PlaybackBegin_pb2'
  # @@protoc_insertion_point(class_scope:PlaybackBegin.PlaybackBegin)
  })
_sym_db.RegisterMessage(PlaybackBegin)
_sym_db.RegisterMessage(PlaybackBegin.Stream)


# @@protoc_insertion_point(module_scope)
