# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Redirect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Redirect.proto',
  package='Redirect',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eRedirect.proto\x12\x08Redirect\"0\n\x08Redirect\x12\x0f\n\x07NewHost\x18\x01 \x02(\t\x12\x13\n\x0bIsTranscode\x18\x02 \x02(\x08'
)




_REDIRECT = _descriptor.Descriptor(
  name='Redirect',
  full_name='Redirect.Redirect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='NewHost', full_name='Redirect.Redirect.NewHost', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='IsTranscode', full_name='Redirect.Redirect.IsTranscode', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['Redirect'] = _REDIRECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Redirect = _reflection.GeneratedProtocolMessageType('Redirect', (_message.Message,), {
  'DESCRIPTOR' : _REDIRECT,
  '__module__' : 'Redirect_pb2'
  # @@protoc_insertion_point(class_scope:Redirect.Redirect)
  })
_sym_db.RegisterMessage(Redirect)


# @@protoc_insertion_point(module_scope)
