# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StartPlayback.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='StartPlayback.proto',
  package='StartPlayback',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13StartPlayback.proto\x12\rStartPlayback\"\xa6\x01\n\rStartPlayback\x12\x11\n\tSessionId\x18\x01 \x02(\x05\x12\x0f\n\x07Profile\x18\x02 \x02(\x05\x12\x11\n\tStartTime\x18\x03 \x01(\x01\x12\x12\n\nExternalIp\x18\x04 \x03(\x0c\x12\x14\n\x0c\x45xternalPort\x18\x05 \x01(\x05\x12\x15\n\rOtherProfiles\x18\x06 \x03(\x05\x12\x1d\n\x15ProfileNotFoundAction\x18\x07 \x01(\x05'
)




_STARTPLAYBACK = _descriptor.Descriptor(
  name='StartPlayback',
  full_name='StartPlayback.StartPlayback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='SessionId', full_name='StartPlayback.StartPlayback.SessionId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Profile', full_name='StartPlayback.StartPlayback.Profile', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='StartTime', full_name='StartPlayback.StartPlayback.StartTime', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ExternalIp', full_name='StartPlayback.StartPlayback.ExternalIp', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ExternalPort', full_name='StartPlayback.StartPlayback.ExternalPort', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='OtherProfiles', full_name='StartPlayback.StartPlayback.OtherProfiles', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ProfileNotFoundAction', full_name='StartPlayback.StartPlayback.ProfileNotFoundAction', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=205,
)

DESCRIPTOR.message_types_by_name['StartPlayback'] = _STARTPLAYBACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartPlayback = _reflection.GeneratedProtocolMessageType('StartPlayback', (_message.Message,), {
  'DESCRIPTOR' : _STARTPLAYBACK,
  '__module__' : 'StartPlayback_pb2'
  # @@protoc_insertion_point(class_scope:StartPlayback.StartPlayback)
  })
_sym_db.RegisterMessage(StartPlayback)


# @@protoc_insertion_point(module_scope)
