# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TokenContainer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TokenContainer.proto',
  package='TokenContainer',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14TokenContainer.proto\x12\x0eTokenContainer\"l\n\x0eTokenContainer\x12\x14\n\x0cSessionToken\x18\x01 \x01(\t\x12\x16\n\x0eWwnAccessToken\x18\x02 \x01(\t\x12\x18\n\x10ServiceAccessKey\x18\x03 \x01(\t\x12\x12\n\nOliveToken\x18\x04 \x02(\t'
)




_TOKENCONTAINER = _descriptor.Descriptor(
  name='TokenContainer',
  full_name='TokenContainer.TokenContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='SessionToken', full_name='TokenContainer.TokenContainer.SessionToken', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='WwnAccessToken', full_name='TokenContainer.TokenContainer.WwnAccessToken', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ServiceAccessKey', full_name='TokenContainer.TokenContainer.ServiceAccessKey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='OliveToken', full_name='TokenContainer.TokenContainer.OliveToken', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=148,
)

DESCRIPTOR.message_types_by_name['TokenContainer'] = _TOKENCONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TokenContainer = _reflection.GeneratedProtocolMessageType('TokenContainer', (_message.Message,), {
  'DESCRIPTOR' : _TOKENCONTAINER,
  '__module__' : 'TokenContainer_pb2'
  # @@protoc_insertion_point(class_scope:TokenContainer.TokenContainer)
  })
_sym_db.RegisterMessage(TokenContainer)


# @@protoc_insertion_point(module_scope)
